services:   #службы, которые будут автоматически подниматься в качестве докер-контейнеров в соответствии с теми образами, которые будут тут прописаны.

  database:
    image: "postgres:16" 
    container_name: hillel_support_database
    env_file: ".env"  
    volumes:
      - "pg_data:/var/lib/postgresql/data"   #слева, то что локально : справа то, что в контейнера

  cache:
    image: "redis:latest" 
    container_name: hillel_support_cache


  broker:
    image: "redis:latest" 
    container_name: hillel_support_broker
 

  mailing:
    image: "mailhog/mailhog:latest"
    container_name: hillel_support_mailing
    ports:

      - "8025:8025"


  api: &app  # container_id shortcut for docker compose command
    build:  # область инструкции создания контейнера
      context: . # обозначает директорию, относительно которой будет запускаться команда билда.
      dockerfile: Dockerfile    # специфицируем докерфайл

      # придаем имя будущему образу 
    image: hillel_support
    container_name: hillel_support_api
    ports:   #связываем порты
      - "8000:8000"  # слева порт локальный, справа в контейнере
    env_file: ".env"
    depends_on:
      - database
      - mailing
      - cache
      - broker
    volumes:
      - ./:/app/    


  worker:  
    <<: *app
    container_name: hillel_support_worker
    ports: []
    entrypoint: bash
    command: -c "watchmedo auto-restart --pattern='*.py' --recursive -- celery -A config worker -l INFO"
   

volumes:
  pg_data: {}