version: "3"

services:   #службы, которые будут автоматически подниматься в качестве докер-контейнеров в соответствии с теми образами, которые будут тут прописаны.
  api:  # container_id shortcut for docker compose command
    build:  # область инструкции создания контейнера
      context: . # обозначает директорию, относительно которой будет запускаться команда билда.
      dockerfile: Dockerfile    # специфицируем докерфайл

      # придаем имя будущему образу 
    image: hillel_support
    container_name: hillel_support_api
    ports:   #связываем порты
      - "8000:8000"  # слева порт локальный, справа в контейнере
    env_file: ".env"
    depends_on:
      - database
    volumes:
      - ./:/app/

  database:
    image: "postgres:16" 
    container_name: hillel_support_database
    ports:   # port forwarding/publishing (проброска портов)
      - "5432:5432"
    env_file: ".env"  
    volumes:
      - "pg_data:/var/lib/postgresql/data"   #слева, то что локально : справа то, что в контейнера


  broker:
    image: "redis:latest" 
    container_name: hillel_support_broker
    ports:   # port forwarding/publishing (проброска портов)
      - "6379:6379"
   

volumes:
  pg_data: {}