# Generated by Django 4.2.11 on 2024-05-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_active_activationkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activationkey",
            name="_id",
        ),
    ]
