name: Check code quality

on: [push]

jobs: 
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install dependencies
        run: pip install black ruff isort
      - name: Run formatters
        run: python3 -m black --check . && python3 -m isort --check . 
      - name: Run linter
        run: python3 -m ruff .   
